### ISSUE TITLE
Bug 未登录时仍然发送了获得用户信息的请求，导致报错

### ISSUE THREAD

**Issue by WeepingDogel** [me0w00f/me0w00f_organization_blogger_backend#3]
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/me0w00f_organization_blogger_backend/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/me0w00f_organization_blogger_backend/routers/resources.py", line 129, in get_user_info
    avatar_path = Path(config.STATIC_DIR).joinpath('users', user_uuid)
  File "/usr/lib/python3.10/pathlib.py", line 851, in joinpath
    return self._make_child(args)
  File "/usr/lib/python3.10/pathlib.py", line 616, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not bool
```

**Comment by WeepingDogel** [comment]
I think the problem is caused by frontend, it still send the request whether the user logged or not.
```typescript
    async getUserInfo() {
      if (this.isLogged) {
        try {
          const config = {
            headers: {
              Authorization: 'Bearer ' + localStorage.getItem('token')
            }
          }
          const response = await axios.get<UserInfo>('/api/resources/user_info/get', config)
          this.user_info = response.data
        } catch (error) {
          console.log(error)
        }
      }else{
        console.log("Not logged.");
      }
```
However, if user didn't logged, the server will only respond with a status 401, not 500....

**Comment by WeepingDogel** [comment]
Fixed!
